version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: wacave
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  go-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
